travis:
  secure:
    BINSTAR_TOKEN: Eml9v4gITnjwGPQNAjfHfJLrIvVVfoXzxn+IdgiTuepnmMEainnle8Bsca0xKQzhSQp0xGQYMhNolz+S+RXQxD6sVu/NDC2dQhkgFzAgG3Bruw5O8Tm8rUzN8KGTIfkcVA3zcFHwebqLWtDuXGWXkHJHOr5zgqQj2vjO3IHvBoWmtCTAogRk874DjrIKpDFjRX4rO+iu8HDEWsPgxCoSIDJBlrzvQOSbp0iN9lX7SLc/m8Jddg0JdyHnpsG/0ln97VFmAve+vjsuuPhHz/E3Uk/pP9Sem9/wqGq38759G6Hgx/OvBTpPtKzoKX5Feht0EEQt2DaZ/3SikMOU6xc6cDVe98elt2fgDw0KuAgNRHpHk2l/Ygbp6C4mLBOSFeY+kGwPFr6LqDsMEZbboFLY0UBxXbSNP+MLQ5MVJRTkN3CXcQudBp96pfa6WHbc/mm7ymf4iOEzM0fmuwwHd3pcOGkWUoLbXwHPtcDFGLU9EuamWzOR3A1eRPq1u85bq2tQrzF44EVFyngrR3ulo+bKdd7U1bAlOjGh0u86TvqyKPpDrKJqsZKZsy1Vc+KjlmNMuqpE/6/tRRVIuVO9Lg8gbvh3GzLKwJGFAAimxa7yOnJKPr2liBU2yQ8AYupfBtd/BYy2/4CUJlmDB+SZeq+0kLUPrNpa+VI9z0R2d11K8cU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
